import figlet from 'figlet'

export const FONTS: figlet.Fonts[] = [
  '1Row',
  '3-D',
  '3D Diagonal',
  '3D-ASCII',
  '3x5',
  '4Max',
  '5 Line Oblique',
  'AMC 3 Line',
  'AMC 3 Liv1',
  'AMC AAA01',
  'AMC Neko',
  'AMC Razor',
  'AMC Razor2',
  'AMC Slash',
  'AMC Slider',
  'AMC Thin',
  'AMC Tubes',
  'AMC Untitled',
  'ANSI Regular',
  'ANSI Shadow',
  'ASCII New Roman',
  'Acrobatic',
  'Alligator',
  'Alligator2',
  'Alpha',
  'Alphabet',
  'Arrows',
  'Avatar',
  'B1FF',
  'B1FF',
  'Banner',
  'Banner3-D',
  'Banner3',
  'Banner4',
  'Barbwire',
  'Basic',
  'Bear',
  'Bell',
  'Benjamin',
  'Big Chief',
  'Big Money-ne',
  'Big Money-nw',
  'Big Money-se',
  'Big Money-sw',
  'Big',
  'Bigfig',
  'Binary',
  'Block',
  'Blocks',
  'Bloody',
  'Bolger',
  'Braced',
  'Bright',
  'Broadway KB',
  'Broadway',
  'Bubble',
  'Bulbhead',
  'Caligraphy',
  'Caligraphy2',
  'Calvin S',
  'Cards',
  'Catwalk',
  'Chiseled',
  'Chunky',
  'Coinstak',
  'Cola',
  'Colossal',
  'Computer',
  'Contessa',
  'Contrast',
  'Cosmike',
  'Crawford',
  'Crawford2',
  'Crazy',
  'Cricket',
  'Cursive',
  'Cyberlarge',
  'Cybermedium',
  'Cybersmall',
  'Cygnet',
  'DANC4',
  'DOS Rebel',
  'DWhistled',
  'Dancing Font',
  'Decimal',
  'Def Leppard',
  'Delta Corps Priest 1',
  'Diamond',
  'Diet Cola',
  'Digital',
  'Doh',
  'Doom',
  'Dot Matrix',
  'Double Shorts',
  'Double',
  'Dr Pepper',
  'Efti Chess',
  'Efti Font',
  'Efti Italic',
  'Efti Piti',
  'Efti Robot',
  'Efti Wall',
  'Efti Water',
  'Electronic',
  'Elite',
  'Epic',
  'Fender',
  'Filter',
  'Fire Font-k',
  'Fire Font-s',
  'Flipped',
  'Flower Power',
  'Four Tops',
  'Fraktur',
  'Fun Face',
  'Fun Faces',
  'Fuzzy',
  'Georgi16',
  'Georgia11',
  'Ghost',
  'Ghoulish',
  'Glenyn',
  'Goofy',
  'Gothic',
  'Graceful',
  'Gradient',
  'Graffiti',
  'Greek',
  'Heart Left',
  'Heart Right',
  'Henry 3D',
  'Hex',
  'Hieroglyphs',
  'Hollywood',
  'Horizontal Left',
  'Horizontal Right',
  'ICL-1900',
  'Impossible',
  'Invita',
  'Isometric1',
  'Isometric2',
  'Isometric3',
  'Isometric4',
  'Italic',
  'Ivrit',
  'JS Block Letters',
  'JS Bracket Letters',
  'JS Capital Curves',
  'JS Cursive',
  'JS Stick Letters',
  'Jacky',
  'Jazmine',
  'Jerusalem',
  'Katakana',
  'Kban',
  'Keyboard',
  'Knob',
  'Konto Slant',
  'Konto',
  'LCD',
  'Larry 3D 2',
  'Larry 3D',
  'Lean',
  'Letters',
  'Lil Devil',
  'Line Blocks',
  'Linux',
  'Lockergnome',
  'Madrid',
  'Marquee',
  'Maxfour',
  'Merlin1',
  'Merlin2',
  'Mike',
  'Mini',
  'Mirror',
  'Mnemonic',
  'Modular',
  'Morse',
  'Morse2',
  'Moscow',
  'Mshebrew210',
  'Muzzle',
  'NScript',
  'NT Greek',
  'NV Script',
  'Nancyj-Fancy',
  'Nancyj-Improved',
  'Nancyj-Underlined',
  'Nancyj',
  'Nipples',
  'O8',
  'OS2',
  'Octal',
  'Ogre',
  'Old Banner',
  'Pagga',
  "Patorjk's Cheese",
  'Patorjk-HeX',
  'Pawp',
  'Peaks Slant',
  'Peaks',
  'Pebbles',
  'Pepper',
  'Poison',
  'Puffy',
  'Puzzle',
  'Pyramid',
  'Rammstein',
  'Rectangles',
  'Red Phoenix',
  'Relief',
  'Relief2',
  'Reverse',
  'Roman',
  'Rot13',
  'Rot13',
  'Rotated',
  'Rounded',
  'Rowan Cap',
  'Rozzo',
  'Runic',
  'Runyc',
  'S Blood',
  'SL Script',
  'Santa Clara',
  'Script',
  'Serifcap',
  'Shadow',
  'Shimrod',
  'Short',
  'Slant Relief',
  'Slant',
  'Slide',
  'Small Caps',
  'Small Isometric1',
  'Small Keyboard',
  'Small Poison',
  'Small Script',
  'Small Shadow',
  'Small Slant',
  'Small Tengwar',
  'Small',
  'Soft',
  'Speed',
  'Spliff',
  'Stacey',
  'Stampate',
  'Stampatello',
  'Standard',
  'Star Strips',
  'Star Wars',
  'Stellar',
  'Stforek',
  'Stick Letters',
  'Stop',
  'Straight',
  'Stronger Than All',
  'Sub-Zero',
  'Swamp Land',
  'Swan',
  'Sweet',
  'THIS',
  'Tanja',
  'Tengwar',
  'Term',
  'Test1',
  'The Edge',
  'Thick',
  'Thin',
  'Thorned',
  'Three Point',
  'Ticks Slant',
  'Ticks',
  'Tiles',
  'Tinker-Toy',
  'Tombstone',
  'Train',
  'Trek',
  'Tsalagi',
  'Tubular',
  'Twisted',
  'Two Point',
  'USA Flag',
  'Univers',
  'Varsity',
  'Wavy',
  'Weird',
  'Wet Letter',
  'Whimsy',
  'Wow',
]

type HolidayInfo = {
  date: string
  holiday: string
  font: figlet.Fonts
  color: string
}

const holidays: HolidayInfo[] = [
  { date: '01-01', holiday: "New Year's Day", font: 'Big', color: '#D4AF37' }, // Gold for celebrations
  {
    date: '02-14',
    holiday: "Valentine's Day",
    font: 'Script',
    color: '#FF69B4',
  }, // Pink for love
  {
    date: '03-17',
    holiday: "St. Patrick's Day",
    font: 'Slant',
    color: '#00A86B',
  }, // Green for St. Patrick
  {
    date: '04-01',
    holiday: 'April Fools',
    font: 'Cybermedium',
    color: '#FFD700',
  }, // Yellow for fun
  { date: '04-22', holiday: 'Earth Day', font: 'Doom', color: '#4CAF50' }, // Green for Earth
  { date: '05-01', holiday: 'Labor Day', font: 'Banner', color: '#FF4500' }, // Red for workers
  {
    date: '07-04',
    holiday: 'Independence Day (US)',
    font: 'Standard',
    color: '#B22234',
  }, // Red for US flag
  { date: '10-31', holiday: 'Halloween', font: 'Gothic', color: '#FF7518' }, // Orange for pumpkins
  { date: '11-11', holiday: 'Veterans Day', font: 'Digital', color: '#000080' }, // Navy blue for solemnity
  { date: '12-25', holiday: 'Christmas', font: 'Block', color: '#008000' }, // Green for Christmas trees
  { date: '07-14', holiday: 'Bastille Day', font: 'Bubble', color: '#0055A4' }, // Blue for French flag
  {
    date: '10-03',
    holiday: 'German Unity Day',
    font: 'Caligraphy',
    color: '#FFCE00',
  }, // Gold for Germany's colors
  {
    date: '06-12',
    holiday: 'Russia Day',
    font: 'Cyberlarge',
    color: '#D52B1E',
  }, // Red for Russia's flag
  {
    date: '09-16',
    holiday: 'Mexico Independence Day',
    font: 'Lean',
    color: '#006847',
  }, // Green for Mexico's flag
  {
    date: '05-05',
    holiday: "Children's Day (Japan)",
    font: 'Mini',
    color: '#BC002D',
  }, // Red for Japan's flag
  {
    date: '08-09',
    holiday: 'National Day (Singapore)',
    font: 'Small',
    color: '#ED2939',
  }, // Red for Singapore's flag
  {
    date: '09-01',
    holiday: 'Start of Spring (Australia)',
    font: 'Star Wars',
    color: '#00008B',
  }, // Blue for ocean surrounding Australia
  {
    date: '02-06',
    holiday: 'Waitangi Day (NZ)',
    font: 'Straight',
    color: '#00205B',
  }, // Blue for New Zealand's flag
  {
    date: '10-01',
    holiday: 'China National Day',
    font: '3D Diagonal',
    color: '#DE2910',
  }, // Red for China's flag
  {
    date: '05-17',
    holiday: 'Constitution Day (Norway)',
    font: '3x5',
    color: '#00205B',
  }, // Blue for Norway's flag
  { date: '07-01', holiday: 'Canada Day', font: '4Max', color: '#FF0000' }, // Red for Canada's flag
  {
    date: '12-26',
    holiday: 'Boxing Day',
    font: '5 Line Oblique',
    color: '#D3D3D3',
  }, // Gray for winter
  {
    date: '10-02',
    holiday: 'Gandhi Jayanti (India)',
    font: '3D-ASCII',
    color: '#FF9933',
  }, // Orange for India's flag
  { date: '06-19', holiday: 'Juneteenth', font: '1Row', color: '#31006A' }, // Purple for the flag
  {
    date: '08-15',
    holiday: 'Assumption of Mary',
    font: 'Colossal',
    color: '#8B008B',
  }, // Purple for Mary's robe
  {
    date: '11-01',
    holiday: "All Saints' Day",
    font: 'Contessa',
    color: '#FFD700',
  }, // Gold for heaven
  {
    date: '12-06',
    holiday: 'St. Nicholas Day',
    font: 'Contrast',
    color: '#FF6347',
  }, // Tomato color for St. Nicholas' attire
  {
    date: '11-28',
    holiday: 'Thanksgiving (US)',
    font: 'Doh',
    color: '#D2691E',
  }, // Chocolate color for Thanksgiving's earthy tones
  {
    date: '02-05',
    holiday: 'Chinese New Year',
    font: 'Epic',
    color: '#DC143C',
  }, // Crimson for China's New Year celebrations
  {
    date: '11-05',
    holiday: 'Guy Fawkes Night',
    font: 'Bigfig',
    color: '#FF4500',
  }, // Orange for the fire
]

export function getFontInfo(
  date = new Date(),
  fallbackFont: figlet.Fonts = 'ANSI Regular',
  fallbackColor: string = '#dddddd'
): { font: figlet.Fonts; holiday?: string; color: string } {
  const formattedDate = `${date.getMonth() + 1}-${date.getDate()}`
  console.log(date, formattedDate)
  const holidayInfo = holidays.find((h) => h.date === formattedDate)

  if (holidayInfo) {
    return {
      font: holidayInfo.font,
      holiday: holidayInfo.holiday,
      color: holidayInfo.color,
    }
  } else {
    return { font: fallbackFont, color: fallbackColor }
  }
}

export const listFonts = () => {
  FONTS.forEach((font) => {
    figlet(`rizzdown`, { font }, (err, data) => {
      console.log(`\n\n----${font}----`)
      console.log(data)
    })
  })
}
